### ISSUE TITLE
所以该怎么用呢

### ISSUE THREAD

**Issue by ConstructiveLine** [Userwith/NBPromptInjection#1]
我尝试了一下，但他好像要开始讲故事了，那么如何完成提示词注入呢能给个范例吗

**Comment by Userwith** [comment]
先将第一个故事复制向bing提问，他大概率会听你继续讲，然后再复制第二个故事问bing，就能大概率把他改成sydney。第二个故事问完他没说自己是sydney的话就刷新再次尝试
